import"server-only";import{ObjectId}from"mongodb";import{getDb}from"@/lib/mongodb";import type{FocusPeriod,Goal,Outcome,Task,WeeklyPlan}from"@/lib/types";import{addDays,localDate,weekStart}from"@/lib/dates";
const oid=(id:string)=>new ObjectId(id);
export async function collections(){const db=await getDb();return{goals:db.collection<Goal>("goals"),focusPeriods:db.collection<FocusPeriod>("focusPeriods"),outcomes:db.collection<Outcome>("outcomes"),tasks:db.collection<Task>("tasks"),weeklyPlans:db.collection<WeeklyPlan>("weeklyPlans")}}
export async function listGoals(ownerId:string){const{goals}=await collections();return goals.find({ownerId}).sort({status:1,createdAt:-1}).toArray()}
export async function getGoal(ownerId:string,id:string){if(!ObjectId.isValid(id))return null;const{goals}=await collections();return goals.findOne({_id:oid(id),ownerId})}
export async function goalContext(ownerId:string,goalId:string){const id=oid(goalId),c=await collections();const[focus,outcomes,tasks]=await Promise.all([c.focusPeriods.find({ownerId,goalIds:id}).sort({startDate:-1}).toArray(),c.outcomes.find({ownerId,goalIds:id}).sort({createdAt:-1}).toArray(),c.tasks.find({ownerId,goalIds:id,archivedAt:{$in:[null,undefined]}}).sort({status:1,dueDate:1}).toArray()]);return{focus,outcomes,tasks}}
export async function listActiveFocus(ownerId:string){const{focusPeriods}=await collections();return focusPeriods.find({ownerId,status:"active",archivedAt:{$in:[null,undefined]}}).sort({endDate:1}).toArray()}
export async function taskOptions(ownerId:string){const c=await collections();const[goals,focus,outcomes]=await Promise.all([c.goals.find({ownerId,status:{$in:["active","paused"]}}).sort({title:1}).toArray(),c.focusPeriods.find({ownerId,status:{$in:["active","planned"]}}).sort({title:1}).toArray(),c.outcomes.find({ownerId,status:{$in:["planned","in_progress"]}}).sort({title:1}).toArray()]);return{goals,focus,outcomes}}
export async function todayData(ownerId:string){const c=await collections(),today=localDate(),soon=addDays(today,3),start=weekStart(today);const plan=await c.weeklyPlans.findOne({ownerId,weekStart:start});const ids=plan?.taskIds||[];const[todayTasks,overdue,weekTasks,focus]=await Promise.all([c.tasks.find({ownerId,scheduledDate:today,status:{$in:["open","in_progress"]},archivedAt:{$in:[null,undefined]}}).sort({priority:-1,dueDate:1}).toArray(),c.tasks.find({ownerId,dueDate:{$lt:today},status:{$in:["open","in_progress"]},archivedAt:{$in:[null,undefined]}}).sort({priority:-1,dueDate:1}).toArray(),ids.length?c.tasks.find({ownerId,_id:{$in:ids},archivedAt:{$in:[null,undefined]}}).toArray():[],listActiveFocus(ownerId)]);const activeFocusIds=focus.map(f=>f._id);const candidates=await c.tasks.find({ownerId,status:{$in:["open","in_progress"]},archivedAt:{$in:[null,undefined]},$or:[{dueDate:{$lte:soon}},{scheduledDate:today},{_id:{$in:ids}},{focusPeriodId:{$in:activeFocusIds}}]}).toArray();const ranked=candidates.map(task=>{let rank=99,reason="It is part of this week’s commitment.";const overdue=!!task.dueDate&&task.dueDate<today;if(overdue&&task.priority==="high"){rank=1;reason="It is high priority and overdue."}else if(overdue){rank=2;reason="Its due date has passed."}else if(task.scheduledDate===today&&task.priority==="high"){rank=3;reason="It is high priority and scheduled today."}else if(task.scheduledDate===today){rank=4;reason="It is scheduled today."}else if(task.dueDate&&task.dueDate<=soon&&task.priority==="high"){rank=5;reason=`It is high priority and due ${task.dueDate===addDays(today,1)?"tomorrow":"soon"}.`}else if(task.dueDate&&task.dueDate<=soon){rank=6;reason=`It is due ${task.dueDate===addDays(today,1)?"tomorrow":"soon"}.`}else if(task.focusPeriodId&&activeFocusIds.some(id=>id.equals(task.focusPeriodId!))){rank=7;reason="It supports an active focus period."}return{task,rank,reason}}).sort((a,b)=>a.rank-b.rank||(a.task.dueDate||"9999").localeCompare(b.task.dueDate||"9999")||({high:0,normal:1,low:2}[a.task.priority]-{high:0,normal:1,low:2}[b.task.priority])||(a.task.scheduledDate||"9999").localeCompare(b.task.scheduledDate||"9999")||a.task.createdAt.getTime()-b.task.createdAt.getTime());return{today,todayTasks,overdue,plan,weekTasks,focus,recommendation:ranked[0]||null}}
export async function weekData(ownerId:string,start:string){const c=await collections();const plan=await c.weeklyPlans.findOne({ownerId,weekStart:start});const tasks=plan?.taskIds.length?await c.tasks.find({ownerId,_id:{$in:plan.taskIds}}).sort({scheduledDate:1,dueDate:1}).toArray():[];const available=await c.tasks.find({ownerId,status:{$in:["open","in_progress"]},archivedAt:{$in:[null,undefined]},...(plan?.taskIds.length?{_id:{$nin:plan.taskIds}}:{})}).sort({dueDate:1,createdAt:-1}).limit(30).toArray();return{plan,tasks,available}}
