"use server";
import{ObjectId}from"mongodb";import{z}from"zod";import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{requireUser}from"@/lib/session";import{collections}from"@/lib/data";import{addDays,weekStart}from"@/lib/dates";
const text=z.string().trim().max(2000).optional().transform(v=>v||undefined),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().or(z.literal("")).transform(v=>v||undefined);const ids=(f:FormData,k:string)=>f.getAll(k).map(String).filter(ObjectId.isValid).map(v=>new ObjectId(v));const val=(f:FormData,k:string)=>String(f.get(k)||"").trim();const id=(f:FormData)=>{const v=val(f,"id");return ObjectId.isValid(v)?new ObjectId(v):null};
const goalSchema=z.object({title:z.string().trim().min(1).max(120),description:text,targetDate:date,notes:text,status:z.enum(["active","paused","completed","archived"])});
export async function saveGoal(f:FormData){const user=await requireUser(),c=await collections(),data=goalSchema.parse({title:val(f,"title"),description:val(f,"description"),targetDate:val(f,"targetDate"),notes:val(f,"notes"),status:val(f,"status")||"active"}),now=new Date(),_id=id(f);if(_id)await c.goals.updateOne({_id,ownerId:user.id},{$set:{...data,updatedAt:now,completedAt:data.status==="completed"?now:null,archivedAt:data.status==="archived"?now:null}});else await c.goals.insertOne({...data,ownerId:user.id,createdAt:now,updatedAt:now,completedAt:data.status==="completed"?now:null,archivedAt:data.status==="archived"?now:null} as never);revalidatePath("/goals");if(_id)revalidatePath(`/goals/${_id}`)}
export async function setGoalStatus(f:FormData){const user=await requireUser(),c=await collections(),_id=id(f),status=z.enum(["active","paused","completed","archived"]).parse(val(f,"status")),now=new Date();if(_id)await c.goals.updateOne({_id,ownerId:user.id},{$set:{status,updatedAt:now,completedAt:status==="completed"?now:null,archivedAt:status==="archived"?now:null}});revalidatePath("/goals")}
const focusSchema=z.object({title:z.string().trim().min(1).max(120),description:text,startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),endDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),notes:text,status:z.enum(["planned","active","paused","completed","archived"])}).refine(v=>v.endDate>=v.startDate,{message:"End date must not precede start date"});
export async function saveFocus(f:FormData){const user=await requireUser(),c=await collections(),data=focusSchema.parse({title:val(f,"title"),description:val(f,"description"),startDate:val(f,"startDate"),endDate:val(f,"endDate"),notes:val(f,"notes"),status:val(f,"status")||"planned"}),goalIds=ids(f,"goalIds"),now=new Date(),_id=id(f);if(!goalIds.length)throw new Error("Select at least one goal");if(await c.goals.countDocuments({ownerId:user.id,_id:{$in:goalIds}})!==goalIds.length)throw new Error("Invalid goal");const doc={...data,goalIds,updatedAt:now,archivedAt:data.status==="archived"?now:null};if(_id)await c.focusPeriods.updateOne({_id,ownerId:user.id},{$set:doc});else await c.focusPeriods.insertOne({...doc,ownerId:user.id,createdAt:now} as never);revalidatePath("/goals");goalIds.forEach(g=>revalidatePath(`/goals/${g}`))}
const outcomeSchema=z.object({title:z.string().trim().min(1).max(160),description:text,kind:z.enum(["outcome","milestone"]),targetDate:date,notes:text,status:z.enum(["planned","in_progress","achieved","dropped","archived"])});
export async function saveOutcome(f:FormData){const user=await requireUser(),c=await collections(),data=outcomeSchema.parse({title:val(f,"title"),description:val(f,"description"),kind:val(f,"kind")||"outcome",targetDate:val(f,"targetDate"),notes:val(f,"notes"),status:val(f,"status")||"planned"}),goalIds=ids(f,"goalIds"),focusRaw=val(f,"focusPeriodId"),focusPeriodId=ObjectId.isValid(focusRaw)?new ObjectId(focusRaw):null,now=new Date(),_id=id(f);if(!goalIds.length)throw new Error("Select a goal");const doc={...data,goalIds,focusPeriodId,updatedAt:now,completedAt:data.status==="achieved"?now:null,archivedAt:data.status==="archived"?now:null};if(_id)await c.outcomes.updateOne({_id,ownerId:user.id},{$set:doc});else await c.outcomes.insertOne({...doc,ownerId:user.id,createdAt:now} as never);goalIds.forEach(g=>revalidatePath(`/goals/${g}`));revalidatePath("/today")}
const taskSchema=z.object({title:z.string().trim().min(1).max(180),description:text,scheduledDate:date,dueDate:date,priority:z.enum(["low","normal","high"]),status:z.enum(["open","in_progress","completed","cancelled"]),notes:text,tags:z.string().max(500).optional()});
export async function saveTask(f:FormData){const user=await requireUser(),c=await collections(),data=taskSchema.parse({title:val(f,"title"),description:val(f,"description"),scheduledDate:val(f,"scheduledDate"),dueDate:val(f,"dueDate"),priority:val(f,"priority")||"normal",status:val(f,"status")||"open",notes:val(f,"notes"),tags:val(f,"tags")}),goalIds=ids(f,"goalIds"),focusRaw=val(f,"focusPeriodId"),outcomeRaw=val(f,"outcomeId"),focusPeriodId=ObjectId.isValid(focusRaw)?new ObjectId(focusRaw):null,outcomeId=ObjectId.isValid(outcomeRaw)?new ObjectId(outcomeRaw):null,tags=(data.tags||"").split(",").map(t=>t.trim().toLowerCase()).filter(Boolean),now=new Date(),_id=id(f),week=val(f,"weekStart");const doc={...data,tags,goalIds,focusPeriodId,outcomeId,updatedAt:now,completedAt:data.status==="completed"?now:null};let taskId=_id;if(_id)await c.tasks.updateOne({_id,ownerId:user.id},{$set:doc});else{const result=await c.tasks.insertOne({...doc,ownerId:user.id,createdAt:now,archivedAt:null} as never);taskId=result.insertedId}if(week&&taskId){await c.weeklyPlans.updateOne({ownerId:user.id,weekStart:week},{$setOnInsert:{ownerId:user.id,weekStart:week,weekEnd:addDays(week,6),title:"",focus:"",priorities:[],status:"active",createdAt:now,archivedAt:null},$set:{updatedAt:now},$addToSet:{taskIds:taskId}},{upsert:true})}revalidatePath("/today");revalidatePath("/week");revalidatePath(`/week/${week||weekStart()}`);goalIds.forEach(g=>revalidatePath(`/goals/${g}`))}
export async function setTaskStatus(f:FormData){const user=await requireUser(),c=await collections(),_id=id(f),status=z.enum(["open","in_progress","completed","cancelled"]).parse(val(f,"status")),now=new Date();if(_id)await c.tasks.updateOne({_id,ownerId:user.id},{$set:{status,updatedAt:now,completedAt:status==="completed"?now:null}});revalidatePath("/today");revalidatePath("/week");revalidatePath("/goals")}
export async function rescheduleTask(f:FormData){const user=await requireUser(),c=await collections(),_id=id(f),scheduledDate=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(val(f,"scheduledDate"));if(_id)await c.tasks.updateOne({_id,ownerId:user.id},{$set:{scheduledDate,updatedAt:new Date()}});revalidatePath("/today");revalidatePath("/week")}
export async function archiveTask(f:FormData){const user=await requireUser(),c=await collections(),_id=id(f);if(_id)await c.tasks.updateOne({_id,ownerId:user.id},{$set:{archivedAt:new Date(),updatedAt:new Date()}});revalidatePath("/today");revalidatePath("/week")}
export async function saveWeeklyPlan(f:FormData){const user=await requireUser(),c=await collections(),start=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(val(f,"weekStart")),now=new Date(),priorities=val(f,"priorities").split("\n").map(v=>v.trim()).filter(Boolean);await c.weeklyPlans.updateOne({ownerId:user.id,weekStart:start},{$set:{title:val(f,"title"),focus:val(f,"focus"),priorities,status:"active",updatedAt:now},$setOnInsert:{ownerId:user.id,weekStart:start,weekEnd:addDays(start,6),taskIds:[],createdAt:now,archivedAt:null}},{upsert:true});revalidatePath(`/week/${start}`);redirect(`/week/${start}`)}
export async function addTaskToWeek(f:FormData){const user=await requireUser(),c=await collections(),start=val(f,"weekStart"),taskIdRaw=val(f,"taskId");if(!ObjectId.isValid(taskIdRaw))return;const taskId=new ObjectId(taskIdRaw);if(!await c.tasks.findOne({_id:taskId,ownerId:user.id}))return;await c.weeklyPlans.updateOne({ownerId:user.id,weekStart:start},{$addToSet:{taskIds:taskId},$set:{updatedAt:new Date()}});revalidatePath(`/week/${start}`)}
export async function removeTaskFromWeek(f:FormData){const user=await requireUser(),c=await collections(),start=val(f,"weekStart"),taskIdRaw=val(f,"taskId");if(ObjectId.isValid(taskIdRaw))await c.weeklyPlans.updateOne({ownerId:user.id,weekStart:start},{$pull:{taskIds:new ObjectId(taskIdRaw)},$set:{updatedAt:new Date()}});revalidatePath(`/week/${start}`)}
