import Link from "next/link";
import { ArrowRight, CalendarCheck, Flag } from "lucide-react";
import { requireUser } from "@/lib/session";
import { taskOptions, todayData } from "@/lib/data";
import { prettyDate } from "@/lib/dates";
import { TaskDetails, TaskList } from "@/components/task-list";
import { setTaskStatus } from "@/app/actions";
import { DetailField, DetailSheet } from "@/components/detail-sheet";

export default async function TodayPage() {
  const user = await requireUser();
  const [data, options] = await Promise.all([todayData(user.id), taskOptions(user.id)]);
  const actionable = data.weekTasks.filter((task) => task.status !== "cancelled");
  const done = actionable.filter((task) => task.status === "completed").length;
  const outstanding = actionable.length - done;
  return <div className="container"><p className="eyebrow">{prettyDate(data.today)}</p><h1 className="page-title">Today</h1><p className="muted" style={{ marginTop: 0 }}>A clear view of what matters now.</p>
    {data.focus.length > 0 && <><div className="section-head"><h2>Current focus</h2></div><div className="summary-grid">{data.focus.map((focus) => { const relatedGoals = options.goals.filter((goal) => focus.goalIds.some((id) => id.equals(goal._id))); return <DetailSheet key={focus._id.toString()} title={focus.title} eyebrow="Active focus period" trigger={<div className="card clickable-card"><p className="task-title">{focus.title}</p><p className="muted" style={{ fontSize: 13, margin: "6px 0 0" }}>{prettyDate(focus.startDate)} – {prettyDate(focus.endDate)}</p></div>}><div className="detail-grid"><DetailField label="Status"><span className="pill">{focus.status}</span></DetailField><DetailField label="Dates">{prettyDate(focus.startDate)} – {prettyDate(focus.endDate)}</DetailField>{focus.description && <DetailField label="Description" wide>{focus.description}</DetailField>}<DetailField label="Related goals" wide><div className="detail-pills">{relatedGoals.map((goal) => <span className="pill" key={goal._id.toString()}>{goal.title}</span>)}</div></DetailField>{focus.notes && <DetailField label="Notes" wide>{focus.notes}</DetailField>}</div></DetailSheet>; })}</div></>}
    <div className="section-head"><h2>What should I do next?</h2></div>{data.recommendation ? <div className="card recommendation-card"><span className="recommendation-icon"><Flag size={20}/></span><div style={{ flex: 1 }}><DetailSheet title={data.recommendation.task.title} eyebrow="Recommended task" trigger={<div className="text-trigger"><h3>{data.recommendation.task.title}</h3><p>Recommended because {data.recommendation.reason.charAt(0).toLowerCase() + data.recommendation.reason.slice(1)}</p></div>}><TaskDetails task={data.recommendation.task} options={options}/></DetailSheet></div><form action={setTaskStatus}><input type="hidden" name="id" value={data.recommendation.task._id.toString()}/><input type="hidden" name="status" value="completed"/><button className="btn btn-primary"><span className="hidden sm:inline">Complete</span><ArrowRight size={18}/></button></form></div> : <div className="empty">No actionable task needs your attention.</div>}
    <div className="section-head"><h2>Today’s tasks</h2><span className="pill">{data.todayTasks.length}</span></div><TaskList tasks={data.todayTasks} options={options} empty="No tasks are scheduled today."/>
    {data.overdue.length > 0 && <><div className="section-head"><h2 style={{ color: "var(--danger)" }}>Overdue</h2><span className="pill">{data.overdue.length}</span></div><TaskList tasks={data.overdue} options={options}/></>}
    <div className="section-head"><h2>This week</h2></div><DetailSheet title={data.plan?.title || "This week"} eyebrow={`${prettyDate(data.plan?.weekStart)} – ${prettyDate(data.plan?.weekEnd)}`} trigger={<div className="card weekly-summary clickable-card"><div><CalendarCheck size={20}/><strong>{actionable.length}</strong><span>planned</span></div><div><strong>{done}</strong><span>completed</span></div><div><strong>{outstanding}</strong><span>outstanding</span></div></div>}><div className="stack sheet-sections">{data.plan?.focus && <DetailField label="Weekly focus">{data.plan.focus}</DetailField>}{data.plan?.priorities.length ? <section className="sheet-section"><h3>Priorities</h3><ol>{data.plan.priorities.map((priority) => <li key={priority}>{priority}</li>)}</ol></section> : null}<section className="sheet-section"><h3>Committed tasks</h3>{actionable.length ? <div className="simple-list">{actionable.map((task) => <div key={task._id.toString()}><span>{task.title}</span><span className="pill">{task.status.replace("_", " ")}</span></div>)}</div> : <p className="muted">No tasks committed to this week.</p>}</section><Link className="btn btn-primary" href="/week">Open full weekly plan <ArrowRight size={18}/></Link></div></DetailSheet>
  </div>;
}
