import { Check, ChevronRight, Clock3, RotateCcw } from "lucide-react";
import type { FocusPeriod, Goal, Outcome, Task } from "@/lib/types";
import { archiveTask, rescheduleTask, setTaskStatus } from "@/app/actions";
import { prettyDate } from "@/lib/dates";
import { TaskForm } from "@/components/task-form";
import { DetailField, DetailSheet } from "@/components/detail-sheet";

type TaskOptions = { goals: Goal[]; focus: FocusPeriod[]; outcomes: Outcome[] };

export function TaskList({ tasks, options, empty = "Nothing here." }: { tasks: Task[]; options: TaskOptions; empty?: string }) {
  if (!tasks.length) return <div className="empty">{empty}</div>;
  return <div className="card task-list">{tasks.map((task) => <div className="task-row" key={task._id.toString()}><form action={setTaskStatus}><input type="hidden" name="id" value={task._id.toString()}/><input type="hidden" name="status" value={task.status === "completed" ? "open" : "completed"}/><button className={task.status === "completed" ? "btn btn-secondary" : "btn btn-ghost"} style={{ padding: 7, minHeight: 36 }} title={task.status === "completed" ? "Reopen" : "Complete"}>{task.status === "completed" ? <RotateCcw size={18}/> : <Check size={19}/>}</button></form><DetailSheet title={task.title} eyebrow="Task details" trigger={<div className="task-row-trigger"><div><p className="task-title" style={{ textDecoration: task.status === "completed" ? "line-through" : "none" }}>{task.title}</p><div className="task-meta">{task.priority !== "normal" && <span className="pill">{task.priority}</span>}{task.scheduledDate && <span className="pill"><Clock3 size={12}/> {prettyDate(task.scheduledDate)}</span>}{task.dueDate && <span className="pill" style={{ color: "var(--warning)" }}>Due {prettyDate(task.dueDate)}</span>}{task.tags.map((tag) => <span className="pill" key={tag}>{tag}</span>)}</div></div><ChevronRight className="row-chevron" size={19}/></div>}><TaskDetails task={task} options={options}/></DetailSheet></div>)}</div>;
}

export function TaskDetails({ task, options }: { task: Task; options: TaskOptions }) {
  const relatedGoals = options.goals.filter((goal) => task.goalIds.some((id) => id.equals(goal._id)));
  const focus = options.focus.find((item) => task.focusPeriodId?.equals(item._id));
  const outcome = options.outcomes.find((item) => task.outcomeId?.equals(item._id));
  return <div className="stack sheet-sections"><section className="detail-grid"><DetailField label="Status"><span className="pill">{task.status.replace("_", " ")}</span></DetailField><DetailField label="Priority"><span className="pill">{task.priority}</span></DetailField><DetailField label="Scheduled">{task.scheduledDate ? prettyDate(task.scheduledDate) : null}</DetailField><DetailField label="Due">{task.dueDate ? prettyDate(task.dueDate) : null}</DetailField>{task.description && <DetailField label="Description" wide>{task.description}</DetailField>}{task.notes && <DetailField label="Notes" wide>{task.notes}</DetailField>}<DetailField label="Goals" wide>{relatedGoals.length ? <div className="detail-pills">{relatedGoals.map((goal) => <span className="pill" key={goal._id.toString()}>{goal.title}</span>)}</div> : null}</DetailField><DetailField label="Focus period" wide>{focus?.title}</DetailField><DetailField label="Outcome" wide>{outcome?.title}</DetailField>{task.tags.length > 0 && <DetailField label="Tags" wide><div className="detail-pills">{task.tags.map((tag) => <span className="pill" key={tag}>{tag}</span>)}</div></DetailField>}</section><section className="sheet-section"><h3>Quick reschedule</h3><form action={rescheduleTask} className="sheet-inline-form"><input type="hidden" name="id" value={task._id.toString()}/><input className="input" type="date" name="scheduledDate" defaultValue={task.scheduledDate} required/><button className="btn btn-secondary">Reschedule</button></form></section><details className="sheet-section"><summary>Edit all details</summary><div style={{ marginTop: 14 }}><TaskForm {...options} task={task}/></div></details><section className="sheet-danger"><form action={archiveTask}><input type="hidden" name="id" value={task._id.toString()}/><button className="btn btn-danger">Archive task</button></form></section></div>;
}
