import Link from "next/link";
import { ArrowRight, Plus } from "lucide-react";
import { requireUser } from "@/lib/session";
import { collections, listGoals } from "@/lib/data";
import { GoalForm } from "@/components/goal-forms";
import { setGoalStatus } from "@/app/actions";
import { DetailField, DetailSheet } from "@/components/detail-sheet";
import { prettyDate } from "@/lib/dates";

export default async function GoalsPage() {
  const user = await requireUser();
  const goals = await listGoals(user.id);
  const c = await collections();
  const [focus, outcomes, tasks] = await Promise.all([c.focusPeriods.find({ ownerId: user.id, status: "active" }).toArray(), c.outcomes.find({ ownerId: user.id, status: { $in: ["planned", "in_progress"] } }).toArray(), c.tasks.find({ ownerId: user.id, status: { $in: ["open", "in_progress"] }, archivedAt: { $in: [null, undefined] } }).toArray()]);
  const groups = ["active", "paused", "completed", "archived"] as const;
  return <div className="container"><p className="eyebrow">Direction</p><h1 className="page-title">Goals</h1><p className="muted" style={{ marginTop: 0 }}>Long-term outcomes, grounded in the next useful action.</p><details className="card" style={{ marginTop: 20 }}><summary style={{ cursor: "pointer", fontWeight: 700 }}><Plus size={17} style={{ display: "inline", verticalAlign: "middle" }}/> Create a goal</summary><div style={{ marginTop: 14 }}><GoalForm/></div></details>
    {groups.map((status) => { const items = goals.filter((goal) => goal.status === status); if (!items.length) return null; return <section key={status}><div className="section-head"><h2 style={{ textTransform: "capitalize" }}>{status}</h2><span className="pill">{items.length}</span></div><div className="stack">{items.map((goal) => { const activeFocus = focus.find((item) => item.goalIds.some((id) => id.equals(goal._id))); const nextOutcome = outcomes.find((outcome) => outcome.goalIds.some((id) => id.equals(goal._id))); const openTasks = tasks.filter((task) => task.goalIds.some((id) => id.equals(goal._id))); return <article className="card goal-card" key={goal._id.toString()}><DetailSheet title={goal.title} eyebrow={`${goal.status} goal`} trigger={<div className="goal-card-trigger"><div><h3>{goal.title}</h3>{goal.description && <p>{goal.description}</p>}<div className="task-meta"><span className="pill">Focus: {activeFocus?.title || "None active"}</span><span className="pill">Next: {nextOutcome?.title || "No outcome"}</span><span className="pill">{openTasks.length} open tasks</span></div></div><ArrowRight size={20}/></div>}><div className="stack sheet-sections"><section className="detail-grid"><DetailField label="Status"><span className="pill">{goal.status}</span></DetailField><DetailField label="Checkpoint">{goal.targetDate ? prettyDate(goal.targetDate) : null}</DetailField>{goal.description && <DetailField label="Description" wide>{goal.description}</DetailField>}{goal.notes && <DetailField label="Notes" wide>{goal.notes}</DetailField>}<DetailField label="Active focus" wide>{activeFocus?.title}</DetailField><DetailField label="Next outcome" wide>{nextOutcome?.title}</DetailField></section><section className="sheet-section"><h3>Outstanding tasks</h3>{openTasks.length ? <div className="simple-list">{openTasks.slice(0, 8).map((task) => <div key={task._id.toString()}><span>{task.title}</span><span className="pill">{task.priority}</span></div>)}</div> : <p className="muted">No outstanding tasks.</p>}</section><details className="sheet-section"><summary>Edit goal</summary><div style={{ marginTop: 14 }}><GoalForm goal={goal}/></div></details><Link className="btn btn-primary" href={`/goals/${goal._id}`}>Open full goal <ArrowRight size={18}/></Link></div></DetailSheet><div className="card-actions">{status !== "active" && <StatusButton id={goal._id.toString()} status="active" label="Activate"/>}{status !== "paused" && status !== "archived" && <StatusButton id={goal._id.toString()} status="paused" label="Pause"/>}{status !== "completed" && status !== "archived" && <StatusButton id={goal._id.toString()} status="completed" label="Complete"/>}{status !== "archived" && <StatusButton id={goal._id.toString()} status="archived" label="Archive"/>}</div></article>; })}</div></section>; })}
  </div>;
}

function StatusButton({ id, status, label }: { id: string; status: string; label: string }) { return <form action={setGoalStatus}><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={status}/><button className="btn btn-secondary compact-btn">{label}</button></form>; }
